### ISSUE TITLE
pip install pufferlib gives ValueError: 'pufferlib/extensions.pyx' doesn't match any files

### ISSUE THREAD

**Issue by AwesomeCap** [PufferAI/PufferLib#62]
pip install pufferlib

Collecting pufferlib
  Using cached pufferlib-0.4.5.tar.gz (94 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gym==0.23 (from pufferlib)
  Using cached gym-0.23.0.tar.gz (624 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.23.3 (from pufferlib)
  Using cached numpy-1.23.3-cp311-cp311-macosx_10_9_x86_64.whl (18.1 MB)
Collecting opencv-python==3.4.17.63 (from pufferlib)
  Using cached opencv_python-3.4.17.63-cp36-abi3-macosx_10_15_x86_64.whl (44.2 MB)
Collecting openskill==4.0.0 (from pufferlib)
  Using cached openskill-4.0.0-py3-none-any.whl (42 kB)
INFO: pip is looking at multiple versions of pufferlib to determine which version is compatible with other requirements. This could take a while.
Collecting pufferlib
  Using cached pufferlib-0.4.4.tar.gz (93 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 127, in <module>
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/5z/nfxgl_ps6qlf5tvrct964q980000gn/T/pip-build-env-whr_qia4/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pufferlib/extensions.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by elevatorguy** [comment]
![Image](https://github.com/user-attachments/assets/48d36ed4-b833-4512-bc95-d12e45502196)
